const ACTIONS_TYPE = {
  CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
  CREATE_TASK_RESOLVE: 'CREATE_TASK_RESOLVE',
  CREATE_TASK_REJECT:  'CREATE_TASK_REJECT',

  GET_TASK_REQUEST: 'GET_TASK_REQUEST',
  GET_TASK_RESOLVE: 'GET_TASK_RESOLVE',
  GET_TASK_REJECT:  'GET_TASK_REJECT',

  PATCH_TASK_REQUEST: 'PATCH_TASK_REQUEST',
  PATCH_TASK_RESOLVE: 'PATCH_TASK_RESOLVE',
  PATCH_TASK_REJECT:  'PATCH_TASK_REJECT',

  DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
  DELETE_TASK_RESOLVE: 'DELETE_TASK_RESOLVE',
  DELETE_TASK_REJECT:  'DELETE_TASK_REJECT'
}

export default ACTIONS_TYPE; 